export const FETCH_CART_REQUEST = "FETCH_CART_REQUEST";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_FAILURE = "FETCH_CART_FAILURE";
export const FETCH_CART_CREATE_REQUEST = "FETCH_CART_CREATE_REQUEST";
export const FETCH_CART_DELETE_REQUEST = "FETCH_CART_DELETE_REQUEST";
export const FETCH_CART_UPDATE_REQUEST = "FETCH_CART_UPDATE_REQUEST"
export const RESET_CART = "RESET_CART"
