export const PRODUCTS_BY_CATEGORIES = [
  {
    name: 'Thời trang nam',
    imageUrl: '/assets/images/products-by-category/thoi-trang-nam.jpeg',
    products: [
      {
        name: `Bộ Quần Áo Cộc Tay Nam Lacoste Men's Sport TH3602 00/ GH3601 00 Màu Trắng Xanh Size XS`,
        imageUrl: '/assets/images/products-by-category/thoi-trang-nam-01.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Áo Nỉ Lacoste Men’s Colorblock Piqué Printed Logo Sweatshirt Phối Màu Size S`,
        imageUrl: '/assets/images/products-by-category/thoi-trang-nam-02.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Áo Khoác Lông Vũ Adidas Colorblock Down Jacket GF0060 Màu Đen Size L`,
        imageUrl: '/assets/images/products-by-category/thoi-trang-nam-03.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Áo Sơ Mi Lacoste Men Regular Fit Checked Patterned Navy Blue Shirt CH0145 00 CSB Màu Xanh Navy Size S`,
        imageUrl: '/assets/images/products-by-category/thoi-trang-nam-04.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Bộ Quần Áo Cộc Tay Nam Lacoste Men's Sport TH3602 00/ GH3601 00 Màu Trắng Xanh Size XS`,
        imageUrl: '/assets/images/products-by-category/thoi-trang-nam-01.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Áo Nỉ Lacoste Men’s Colorblock Piqué Printed Logo Sweatshirt Phối Màu Size S`,
        imageUrl: '/assets/images/products-by-category/thoi-trang-nam-02.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Áo Khoác Lông Vũ Adidas Colorblock Down Jacket GF0060 Màu Đen Size L`,
        imageUrl: '/assets/images/products-by-category/thoi-trang-nam-03.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Áo Sơ Mi Lacoste Men Regular Fit Checked Patterned Navy Blue Shirt CH0145 00 CSB Màu Xanh Navy Size S`,
        imageUrl: '/assets/images/products-by-category/thoi-trang-nam-04.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
    ],
  },
  {
    name: 'Nước hoa',
    imageUrl: '/assets/images/products-by-category/nuoc-hoa.jpeg',
    products: [
      {
        name: `Nước Hoa ISSEY MIYAKE NECTAR D'ISSEY PREMIÈRE FLEUR EAU DE PARFUM (50ml)`,
        imageUrl: '/assets/images/products-by-category/nuoc-hoa-01.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Nước Hoa ISSEY MIYAKE L'EAU D'ISSEY PURE NECTAR DE PARFUM EAU DE PARFUM (30ml)`,
        imageUrl: '/assets/images/products-by-category/nuoc-hoa-02.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Nước Hoa ISSEY MIYAKE NECTAR D'ISSEY PREMIÈRE FLEUR EAU DE PARFUM (50ml)`,
        imageUrl: '/assets/images/products-by-category/nuoc-hoa-03.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Nước Hoa ISSEY MIYAKE L'EAU D'ISSEY ROSE&ROSE EAU DE PARFUM INTENSE (90ml)`,
        imageUrl: '/assets/images/products-by-category/nuoc-hoa-04.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Nước Hoa ISSEY MIYAKE NECTAR D'ISSEY PREMIÈRE FLEUR EAU DE PARFUM (50ml)`,
        imageUrl: '/assets/images/products-by-category/nuoc-hoa-01.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Nước Hoa ISSEY MIYAKE L'EAU D'ISSEY PURE NECTAR DE PARFUM EAU DE PARFUM (30ml)`,
        imageUrl: '/assets/images/products-by-category/nuoc-hoa-02.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Nước Hoa ISSEY MIYAKE NECTAR D'ISSEY PREMIÈRE FLEUR EAU DE PARFUM (50ml)`,
        imageUrl: '/assets/images/products-by-category/nuoc-hoa-03.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Nước Hoa ISSEY MIYAKE L'EAU D'ISSEY ROSE&ROSE EAU DE PARFUM INTENSE (90ml)`,
        imageUrl: '/assets/images/products-by-category/nuoc-hoa-04.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
    ],
  },
  {
    name: 'Giày dép',
    imageUrl: '/assets/images/products-by-category/giay-dep.png',
    products: [
      {
        name: `Giày Thể Thao Duca Di Morrone ZACK_BLACK-GOLD Màu Đen Phối Vàng Size 41`,
        imageUrl: '/assets/images/products-by-category/giay-dep-01.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Giày Thể Thao Duca Di Morrone 405_CRUST_GRIGIO Màu Xám Size 40`,
        imageUrl: '/assets/images/products-by-category/giay-dep-02.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `MLB - Giày mule unisex đế bệt Playball Origin`,
        imageUrl: '/assets/images/products-by-category/giay-dep-03.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `MLB - Giày mule unisex đế bệt Playball Origin`,
        imageUrl: '/assets/images/products-by-category/giay-dep-04.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Giày Thể Thao Duca Di Morrone ZACK_BLACK-GOLD Màu Đen Phối Vàng Size 41`,
        imageUrl: '/assets/images/products-by-category/giay-dep-01.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Giày Thể Thao Duca Di Morrone 405_CRUST_GRIGIO Màu Xám Size 40`,
        imageUrl: '/assets/images/products-by-category/giay-dep-02.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `MLB - Giày mule unisex đế bệt Playball Origin`,
        imageUrl: '/assets/images/products-by-category/giay-dep-03.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `MLB - Giày mule unisex đế bệt Playball Origin`,
        imageUrl: '/assets/images/products-by-category/giay-dep-04.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
    ],
  },
  {
    name: 'Túi xách',
    imageUrl: '/assets/images/products-by-category/tui-xach.jpeg',
    products: [
      {
        name: `Ví đựng điện thoại đeo chéo Kate Spade New York spade flower jacquard`,
        imageUrl: '/assets/images/products-by-category/tui-xach-01.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Ví đựng mỹ phẩm Kate Spade New York sam icon KSNYL (Ks Green)`,
        imageUrl: '/assets/images/products-by-category/tui-xach-02.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Ví đeo chéo Kate Spade New York Spade Flower Jacquard cỡ trung (CREAM MULTI)`,
        imageUrl: '/assets/images/products-by-category/tui-xach-03.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Ví đeo chéo Kate Spade New York Morgan Double Up (Black)`,
        imageUrl: '/assets/images/products-by-category/tui-xach-04.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Ví đựng điện thoại đeo chéo Kate Spade New York spade flower jacquard`,
        imageUrl: '/assets/images/products-by-category/tui-xach-01.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Ví đựng mỹ phẩm Kate Spade New York sam icon KSNYL (Ks Green)`,
        imageUrl: '/assets/images/products-by-category/tui-xach-02.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Ví đeo chéo Kate Spade New York Spade Flower Jacquard cỡ trung (CREAM MULTI)`,
        imageUrl: '/assets/images/products-by-category/tui-xach-03.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Ví đeo chéo Kate Spade New York Morgan Double Up (Black)`,
        imageUrl: '/assets/images/products-by-category/tui-xach-04.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
    ],
  },
  {
    name: 'Mỹ phẩm',
    imageUrl: '/assets/images/products-by-category/my-pham.jpeg',
    products: [
      {
        name: `Set Son MAC Lashes To Lips Kit Velet Teddy Stack Neutral 3 Món`,
        imageUrl: '/assets/images/products-by-category/my-pham-01.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Son Dior Rouge Lipstick Satin Mini Màu 999 Đỏ Tươi`,
        imageUrl: '/assets/images/products-by-category/my-pham-02.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Toner BHA Obagi Clenziderm MD Pore Therapy 2% 148ml, Giảm Mụn Nhờn`,
        imageUrl: '/assets/images/products-by-category/my-pham-03.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Kem Dưỡng Hỗ Trợ Da Trẻ Hóa, Giảm Mụn Obagi 360 1.0% 28g`,
        imageUrl: '/assets/images/products-by-category/my-pham-04.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Set Son MAC Lashes To Lips Kit Velet Teddy Stack Neutral 3 Món`,
        imageUrl: '/assets/images/products-by-category/my-pham-01.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Son Dior Rouge Lipstick Satin Mini Màu 999 Đỏ Tươi`,
        imageUrl: '/assets/images/products-by-category/my-pham-02.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Toner BHA Obagi Clenziderm MD Pore Therapy 2% 148ml, Giảm Mụn Nhờn`,
        imageUrl: '/assets/images/products-by-category/my-pham-03.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
      {
        name: `Kem Dưỡng Hỗ Trợ Da Trẻ Hóa, Giảm Mụn Obagi 360 1.0% 28g`,
        imageUrl: '/assets/images/products-by-category/my-pham-04.png',
        discount_price: '5.250.000đ',
        price: '3.234.000đ',
      },
    ],
  },
];
