export const GET_LIST_NOTIFICATION = "GET_LIST_NOTIFICATION"
export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION"
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION"
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION"
export const RESET_NOTIFICATION = "RESET_NOTIFICATION"
export const SET_NOTIFICATION = "SET_NOTIFICATION"
export const SET_SUCCESS_NOTIFICATION = "SET_SUCCESS_NOTIFICATION"
export const SET_FAIL_NOTIFICATION = "SET_FAIL_NOTIFICATION"
export const SET_LOADING_NOTIFICATION = "SET_LOADING_NOTIFICATION"

// API
export const GET_LIST_NOTIFICATION_API_CLIENT = "/notification/get-notifications-client"
export const UPDATE_NOTIFICATION_STATUS_API = "/notification/update-notification-status-client"
export const READ_ALL_NOTIFICATION = "/notification/read-all-notification"